#!/bin/bash

# Create labels in all configured repositories
# This script reads the repository list from ai-bot-config.yml

echo "🏷️  AI-Dev-Bot Label Creation"
echo "=============================="
echo ""

REPOS=(
  "fok666/selfhosted-devops"
  "fok666/github-selfhosted-runner"
  "fok666/gitlab-selfhosted-runner"
  "fok666/azure-devops-agent"
  "fok666/lambda-python-layer"
  "fok666/openhqm"
  "fok666/openhqm-rm"
  "fok666/openhqm-dashboard"
  "fok666/aws-lambda-astrolog"
)

create_labels_for_repo() {
  local repo=$1
  echo "📦 Creating labels in $repo..."
  
  # Priority labels
  gh label create priority-high --repo "$repo" --color d73a4a --description "High priority task" --force 2>/dev/null || true
  gh label create priority-medium --repo "$repo" --color fbca04 --description "Medium priority task" --force 2>/dev/null || true
  gh label create priority-low --repo "$repo" --color 0e8a16 --description "Low priority task" --force 2>/dev/null || true
  
  # Status labels
  gh label create status-ready --repo "$repo" --color 0e8a16 --description "Ready for bot to pick up" --force 2>/dev/null || true
  gh label create status-in-progress --repo "$repo" --color fbca04 --description "Bot is working on this" --force 2>/dev/null || true
  gh label create status-blocked --repo "$repo" --color d73a4a --description "Blocked, cannot proceed" --force 2>/dev/null || true
  gh label create status-review --repo "$repo" --color 5319e7 --description "Awaiting review" --force 2>/dev/null || true
  gh label create status-done --repo "$repo" --color 0e8a16 --description "Completed" --force 2>/dev/null || true
  
  # Complexity labels
  gh label create complexity-S --repo "$repo" --color c5def5 --description "Small task (<2 hours)" --force 2>/dev/null || true
  gh label create complexity-M --repo "$repo" --color 5ebeff --description "Medium task (2-8 hours)" --force 2>/dev/null || true
  gh label create complexity-L --repo "$repo" --color 1f77b4 --description "Large task (8-24 hours, consider splitting)" --force 2>/dev/null || true
  
  # Type labels
  gh label create type-feature --repo "$repo" --color a2eeef --description "New feature" --force 2>/dev/null || true
  gh label create type-bugfix --repo "$repo" --color d73a4a --description "Bug fix" --force 2>/dev/null || true
  gh label create type-refactor --repo "$repo" --color fef2c0 --description "Code refactoring" --force 2>/dev/null || true
  gh label create type-docs --repo "$repo" --color 1d76db --description "Documentation" --force 2>/dev/null || true
  gh label create type-test --repo "$repo" --color bfdadc --description "Test improvements" --force 2>/dev/null || true
  gh label create type-investigate --repo "$repo" --color e99695 --description "Pipeline failure investigation" --force 2>/dev/null || true
  gh label create type-ci-cd --repo "$repo" --color 1d76db --description "CI/CD pipeline related" --force 2>/dev/null || true
  
  # Special labels
  gh label create ai-bot-task --repo "$repo" --color 7057ff --description "Task for AI bot" --force 2>/dev/null || true
  gh label create ai-generated --repo "$repo" --color e4e669 --description "Generated by AI bot" --force 2>/dev/null || true
  gh label create automated --repo "$repo" --color bfdadc --description "Automated change" --force 2>/dev/null || true
  gh label create pipeline-failure --repo "$repo" --color d73a4a --description "Auto-created from workflow failure" --force 2>/dev/null || true
  gh label create bot-improvement --repo "$repo" --color 7057ff --description "Bot self-improvement proposal" --force 2>/dev/null || true
  gh label create bot-memory --repo "$repo" --color f9d0c4 --description "Issue used for memory storage" --force 2>/dev/null || true
  gh label create automated-investigation --repo "$repo" --color ff6b6b --description "Automated issue creation" --force 2>/dev/null || true
  gh label create needs-review --repo "$repo" --color fbca04 --description "Needs human review" --force 2>/dev/null || true
  
  echo "   ✓ Labels created/updated in $repo"
  echo ""
}

# Check if gh CLI is available
if ! command -v gh &> /dev/null; then
  echo "❌ Error: GitHub CLI (gh) is not installed"
  echo "Install from: https://cli.github.com/"
  exit 1
fi

# Check if authenticated
if ! gh auth status &> /dev/null; then
  echo "❌ Error: Not authenticated with GitHub CLI"
  echo "Run: gh auth login"
  exit 1
fi

echo "Creating labels in ${#REPOS[@]} repositories..."
echo ""

success_count=0
error_count=0

for repo in "${REPOS[@]}"; do
  if create_labels_for_repo "$repo"; then
    ((success_count++))
  else
    ((error_count++))
    echo "   ✗ Error creating labels in $repo"
  fi
done

echo ""
echo "=============================="
echo "✅ Label creation complete!"
echo ""
echo "📊 Summary:"
echo "   Successfully processed: $success_count repositories"
if [ $error_count -gt 0 ]; then
  echo "   Errors: $error_count repositories"
fi
echo ""
echo "🔍 Verify labels were created:"
echo "   gh label list --repo <repo-name>"
