#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { Octokit } from '@octokit/rest';
import { getGeminiService } from './gemini-service.js';

/**
 * PR Manager - Handles pull request operations
 */
class PRManager {
  constructor() {
    this.octokit = new Octokit({
      auth: process.env.GH_API_TOKEN || process.env.GITHUB_TOKEN
    });

    this.gemini = getGeminiService();

    const repoEnv = process.env.GITHUB_REPOSITORY || '';
    const [owner, repo] = repoEnv.split('/');
    this.owner = owner || 'kornfer';
    this.repo = repo || 'ai-dev-bot';
  }

  /**
   * Create a pull request (supports cross-repo)
   */
  async create(branch, title, issueNumber = null, targetOwner = null, targetRepo = null) {
    try {
      const owner = targetOwner || this.owner;
      const repo = targetRepo || this.repo;
      
      console.log(`📝 Creating PR in ${owner}/${repo} from branch ${branch}...`);

      // Load plan if available
      let body = `## AI-Generated Implementation

This PR was automatically created by the AI-Dev-Bot.
`;

      if (issueNumber) {
        body += `\nCloses #${issueNumber}\n`;

        // Try multiple plan file formats (with and without repo context)
        const planFiles = [
          path.join(process.cwd(), '.context-cache', `plan-${owner}-${repo}-${issueNumber}.json`),
          path.join(process.cwd(), '.context-cache', `plan-${issueNumber}.json`)
        ];

        let plan = null;
        for (const planFile of planFiles) {
          if (fs.existsSync(planFile)) {
            plan = JSON.parse(fs.readFileSync(planFile, 'utf8'));
            break;
          }
        }

        if (plan) {
          body += `\n## Implementation Plan

**Approach:**
${plan.approach}

**Key Changes:**
${plan.files.slice(0, 5).map(f => `- ${f}`).join('\n')}

**Testing:**
${plan.testing}

## Checklist
- [x] Implementation complete
- [x] Plan documented
- [ ] Manual review required

---
🤖 Generated by AI-Dev-Bot using Gemini 3.0 Flash
`;
        }
      }

      const { data: pr } = await this.octokit.pulls.create({
        owner,
        repo,
        title,
        body,
        head: branch,
        base: 'main',
        draft: false
      });

      console.log(`✅ PR created: ${owner}/${repo}#${pr.number}`);
      console.log(`   URL: ${pr.html_url}`);
      
      if (process.env.GITHUB_OUTPUT) {
        fs.appendFileSync(process.env.GITHUB_OUTPUT, `pr_number=${pr.number}\n`);
        fs.appendFileSync(process.env.GITHUB_OUTPUT, `pr_url=${pr.html_url}\n`);
      } else {
        console.log(`::set-output name=pr_number::${pr.number}`);
        console.log(`::set-output name=pr_url::${pr.html_url}`);
      }

      // Add labels
      await this.octokit.issues.addLabels({
        owner: this.owner,
        repo: this.repo,
        issue_number: pr.number,
        labels: ['ai-generated', 'automated']
      });

      return pr;
    } catch (error) {
      console.error('Error creating PR:', error.message);
      throw error;
    }
  }

  /**
   * Review a pull request
   */
  async review(prNumber, sddPath = 'SDD.md') {
    try {
      console.log(`👀 Reviewing PR #${prNumber}...`);

      // Get PR details
      const { data: pr } = await this.octokit.pulls.get({
        owner: this.owner,
        repo: this.repo,
        pull_number: prNumber
      });

      // Get PR diff
      const { data: files } = await this.octokit.pulls.listFiles({
        owner: this.owner,
        repo: this.repo,
        pull_number: prNumber
      });

      // Build review prompt
      const sdd = fs.existsSync(sddPath) ? fs.readFileSync(sddPath, 'utf8').substring(0, 2000) : '';
      
      const prompt = `You are a senior code reviewer.

PR: #${prNumber} - ${pr.title}
Author: ${pr.user.login}
Changes: ${pr.changed_files} files, +${pr.additions}/-${pr.deletions} lines

Files changed:
${files.slice(0, 10).map(f => `- ${f.filename} (+${f.additions}/-${f.deletions})`).join('\n')}

SDD Guidelines (excerpt):
${sdd}

Provide a brief review assessment:
1. Overall quality (Good/Needs Improvement)
2. Any concerns or suggestions (max 3 points)
3. Decision: APPROVE, REQUEST_CHANGES, or COMMENT

Keep response concise (under 200 words).`;

      const reviewText = await this.gemini.generate(prompt);

      console.log('\n📋 Review generated:\n');
      console.log(reviewText);

      // Determine review action
      let action = 'COMMENT';
      if (reviewText.includes('APPROVE')) action = 'APPROVE';
      if (reviewText.includes('REQUEST_CHANGES')) action = 'REQUEST_CHANGES';

      console.log(`\n✅ Review decision: ${action}`);
      
      // Note: GitHub Actions cannot approve PRs, action will be converted to COMMENT in workflow
      if (action === 'APPROVE' && process.env.GITHUB_ACTIONS) {
        console.log('⚠️  Note: GitHub Actions cannot approve PRs - recommendation will be posted as comment');
      }
      
      if (process.env.GITHUB_OUTPUT) {
        fs.appendFileSync(process.env.GITHUB_OUTPUT, 'should_review=true\n');
        fs.appendFileSync(process.env.GITHUB_OUTPUT, `review_body=${reviewText.replace(/\n/g, ' ')}\n`);
        fs.appendFileSync(process.env.GITHUB_OUTPUT, `review_action=${action}\n`);
      } else {
        console.log(`::set-output name=should_review::true`);
        console.log(`::set-output name=review_body::${reviewText.replace(/\n/g, ' ')}`);
        console.log(`::set-output name=review_action::${action}`);
      }

      return { action, body: reviewText };
    } catch (error) {
      console.error('Error reviewing PR:', error.message);
      throw error;
    }
  }

  /**
   * Check if PR can be merged
   */
  async checkMergeConditions(prNumber) {
    try {
      console.log(`🔍 Checking merge conditions for PR #${prNumber}...`);

      // Get PR details
      const { data: pr } = await this.octokit.pulls.get({
        owner: this.owner,
        repo: this.repo,
        pull_number: prNumber
      });

      const canMerge = pr.mergeable && 
                      !pr.draft && 
                      pr.mergeable_state === 'clean';

      if (process.env.GITHUB_OUTPUT) {
        fs.appendFileSync(process.env.GITHUB_OUTPUT, `can_merge=${canMerge}\n`);
      } else {
        console.log(`::set-output name=can_merge::${canMerge}`);
      }
      console.log(`✅ Can merge: ${canMerge}`);

      return canMerge;
    } catch (error) {
      console.error('Error checking merge conditions:', error.message);
      throw error;
    }
  }
}

// CLI interface
async function main() {
  const command = process.argv[2];
  const manager = new PRManager();

  try {
    switch (command) {
      case 'create':
        const branch = process.argv.find(arg => arg.startsWith('--branch='))?.split('=')[1];
        const title = process.argv.find(arg => arg.startsWith('--title='))?.split('=')[1];
        const issue = process.argv.find(arg => arg.startsWith('--issue='))?.split('=')[1];
        const targetOwner = process.argv.find(arg => arg.startsWith('--target-owner='))?.split('=')[1];
        const targetRepo = process.argv.find(arg => arg.startsWith('--target-repo='))?.split('=')[1];

        if (!branch || !title) {
          console.error('Error: --branch=<name> and --title=<text> required');
          process.exit(1);
        }

        await manager.create(
          branch, 
          title, 
          issue ? parseInt(issue) : null,
          targetOwner,
          targetRepo
        );
        break;

      case 'review':
        const prNumber = process.argv.find(arg => arg.startsWith('--pr-number='))?.split('=')[1];
        const sddPath = process.argv.find(arg => arg.startsWith('--sdd-path='))?.split('=')[1] || 'SDD.md';

        if (!prNumber) {
          console.error('Error: --pr-number=<number> required');
          process.exit(1);
        }

        await manager.review(parseInt(prNumber), sddPath);
        break;

      case 'check-merge-conditions':
        const checkPR = process.argv.find(arg => arg.startsWith('--pr-number='))?.split('=')[1];
        if (!checkPR) {
          console.error('Error: --pr-number=<number> required');
          process.exit(1);
        }
        await manager.checkMergeConditions(parseInt(checkPR));
        break;

      default:
        console.error('Unknown command:', command);
        console.error('Available commands: create, review, check-merge-conditions');
        process.exit(1);
    }
  } catch (error) {
    console.error('Fatal error:', error.message);
    process.exit(1);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}

export default PRManager;
